### ISSUE TITLE
Disable database public access

### ISSUE THREAD

**Issue by uolter** [pagopa/corporate-site-infrastructure#10]
https://github.com/pagopa/corporate-site-infrastructure/blob/46193959b8116e377ba1f55c07ab4a24fd999eff/src/database.tf#L32

@nottix why this settings? 
public_network_access_enabled    = true

I am expecting vnet integration. 
- The db server should have its subnet.
- Only the cms subnet should have access to db server. 
(Indeed you created the private endpoint ).   (cc @pasqualedevita )

**Comment by pasqualedevita** [comment]
done in https://github.com/pagopa/corporate-site-infrastructure/pull/9/commits/ca6f5903c6edfb92589f984dc745f2f1eed2075c
